### ISSUE TITLE
Question: What is the relationship of this fork to the original yhat/pandasql?

### ISSUE THREAD

**Issue by javadba** [airtoxin/pysqldf#11]
The yhat/pandasql has limited maintainers attention so I am looking for offshoots/forks that might be more active. Am I in the right place?

**Comment by airtoxin** [comment]
This is a private fork of yhat/pandasql.
I want function of udf in pandasql but its repository is not active. So I forked that.
If you have a issue, I'll try to fix that but I can't promise to fix because this repository also have not been actived anymore...

**Comment by javadba** [comment]
Thx - that was my suspicion.  If you run across a more actively maintained  fork of pandasql down the road would you mind to re-post here?  I love it for what *does* work - but sqlite is a limited and buggy sql dialect so we end up in trouble pretty often ;)
